version: "3.9"

services:
  db:
    image: postgres:13.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=testing321
      - POSTGRES_DB=mydb
    ports:
      - 5432:5432
    volumes:
      - ./db-data/pg-data:/var/lib/postgresql/data/ # persist data even if container shuts down

  redis:
    image: redis:alpine

  celery:
    build: .
    volumes:
      - ./:/usr/src/app
    command: celery -A config.celery:app worker -l info
    depends_on:
      - db
      - redis
#      - app

#  app:
#    build: .
#    command: sh /usr/src/app/entrypoint.sh
#    volumes:
#      - ./:/usr/src/app
#    depends_on:
#      - db
#    ports:
#      - 8000:8000

volumes:
  db_data: