# Generated by Django 3.2.6 on 2021-08-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0002_auto_20210820_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'Processing'), ('READY', 'Ready'), ('ERROR', 'Error')], default='PROCESSING', max_length=50),
        ),
    ]
