# Generated by Django 3.2.6 on 2021-08-29 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0005_job_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='url',
            new_name='file_url',
        ),
    ]
